import { StyleSheet } from 'react-native';
import { colors, spacing, typography } from '@mobile/ui/theme/tokens';
const ALT_THUMBNAIL = 76;

export const styles = StyleSheet.create({
  hero: {
    backgroundColor: '#131315',
    borderRadius: 26,
    boxShadow: '0px 22px 46px rgba(0, 0, 0, 0.62)',
    overflow: 'hidden',
  },
  visual: {
    aspectRatio: 362 / 372,
    backgroundColor: '#222224',
    position: 'relative',
    width: '100%',
  },
  veil: {
    backgroundColor: 'rgba(9, 9, 10, 0.58)',
    pointerEvents: 'none',
    bottom: 0,
    left: 0,
    position: 'absolute',
    right: 0,
    top: 0,
  },
  pillAnchor: {
    alignItems: 'flex-start',
    left: 14,
    position: 'absolute',
    top: 14,
  },
  nameAnchor: {
    bottom: 18,
    gap: 7,
    left: 18,
    position: 'absolute',
    right: 18,
  },
  category: {
    color: colors.lime,
    fontSize: 11,
    fontWeight: '700',
    letterSpacing: 1.5,
  },
  categoryDim: {
    color: '#7f8a5c',
    fontSize: 11,
    fontWeight: '700',
    letterSpacing: 1.5,
  },
  name: {
    color: '#f4f3ee',
    fontSize: 27,
    letterSpacing: -0.324,
    fontWeight: '800',
    lineHeight: 34,
  },
  nameDim: {
    color: '#d3d2cd',
    fontSize: 27,
    letterSpacing: -0.324,
    fontWeight: '800',
    lineHeight: 34,
  },
  heading: {
    overflow: 'hidden',
    backgroundColor: '#1c1c20',
    gap: 14,
    paddingBottom: 18,
    paddingHorizontal: 18,
    paddingTop: 18,
  },
  headingGradient: { ...StyleSheet.absoluteFill },
  headingText: {
    gap: 7,
  },
  body: {
    paddingBottom: 18,
    paddingHorizontal: 18,
    paddingTop: 16,
  },
  actionRow: {
    flexDirection: 'row',
    gap: spacing.compact,
    marginTop: 16,
  },
  primaryAction: {
    flexDirection: 'row',
    gap: 6,
    paddingHorizontal: 12,
    paddingVertical: 10,
    alignItems: 'center',
    backgroundColor: colors.cream,
    borderRadius: 15,
    flexGrow: 1,
    justifyContent: 'center',
    minHeight: 50,
  },
  primaryActionText: {
    color: colors.ink,
    fontSize: typography.button,
    fontWeight: '700',
  },
  secondaryAction: {
    gap: 3,
    paddingVertical: 8,
    alignItems: 'center',
    borderColor: colors.border,
    borderRadius: 15,
    borderWidth: 1,
    justifyContent: 'center',
    minHeight: 50,
    width: 84,
  },
  secondaryActionText: {
    color: colors.muted,
    fontSize: 11,
    fontWeight: '700',
  },
  footnote: {
    marginTop: 14,
    color: '#7c7b76',
    flexShrink: 1,
    fontSize: 11,
    lineHeight: 16,
  },
  alternative: {
    alignItems: 'center',
    backgroundColor: '#131315',
    borderRadius: 20,
    flexDirection: 'row',
    gap: 12,
    minHeight: 96,
    padding: 10,
  },
  thumbnail: {
    borderRadius: 15,
    height: ALT_THUMBNAIL,
    overflow: 'hidden',
    width: ALT_THUMBNAIL,
  },
  alternativeBody: {
    flex: 1,
    gap: 4,
    minWidth: 0,
  },
  alternativeName: {
    color: colors.text,
    fontSize: typography.body,
    fontWeight: '700',
  },
  alternativeDiff: {
    color: '#b9b8b1',
    fontSize: typography.label,
  },
  alternativeMeta: {
    color: '#8f8e88',
    fontSize: 11,
  },
  disabled: { opacity: 0.45 },
  pressed: {
    opacity: 0.72,
  },
});
