/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=workers/api/wrangler.runtime-test.jsonc --include-runtime=false --env-interface=RuntimeGateEnv workers/api/tests/runtime-gate/runtime-env.d.ts` (hash: 5dff31486b305f76884bfcf2ac4f13cc)
interface __BaseEnv_RuntimeGateEnv {
	RUNTIME_GATE: DurableObjectNamespace<import("./runtime-gate-worker").RuntimeGateAgent>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./runtime-gate-worker");
		durableNamespaces: "RuntimeGateAgent";
	}
	interface Env extends __BaseEnv_RuntimeGateEnv {}
}
interface RuntimeGateEnv extends __BaseEnv_RuntimeGateEnv {}
